org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=256m -XX:+UseSerialGC
org.gradle.daemon=false
kotlin.compiler.execution.strategy=in-process

kotlin_version = 1.6.10
detekt_version = 1.19.0
forgeVersion=1.8.9-11.15.1.2318-1.8.9
forgegradle_version = f2c5bb338e
mixingradle_version = ae2a80e
jcef_version = 100.0.14.2
